image: lobis/root-geant4-garfieldpp:cxx14_ROOTv6-25-01_Geant4v10.4.3

variables:
      GIT_SUBMODULE_STRATEGY: recursive

stages:
  - pre-build
  - build
  - loadRESTLibs
  - metadata

before_script:
    - export USER="axion"
      #    - git submodule sync --recursive
      #    - git submodule update --init --recursive

clang-format:
    stage: pre-build
    script:
        - echo "**$CRONJOB**"
        - echo "**$CI_SERVER_HOST**"
        - cd ${CI_PROJECT_DIR}/pipeline/clang-format/
        - ./clangformattest.sh
          # We execute only at a schedulled pipeline that defines CRONJOB variable
    only:
        variables:
            - $CRONJOB

validateLibrary:
    stage: pre-build
    script:
        - python pipeline/validateLibrary.py .
    except:
        variables:
            - $CRONJOB == "YES"

build:
  type: build
  script:
    - echo "**${CI_PROJECT_DIR}**"
    - rm -rf ${CI_PROJECT_DIR}/install
    - git clone --single-branch --branch development https://github.com/rest-for-physics/framework.git framework
    - cd framework
    - python3.5 pull-submodules.py --force --lfna --dontask
    - cd source/libraries/axion/
    - git checkout ${CI_COMMIT_BRANCH}
    - git submodule update --init --recursive
    - cd ../../../
    - mkdir build
    - cd build
    - cmake ../ -DREST_WELCOME=ON -DRESTLIB_AXION=ON -DREST_GARFIELD=OFF -DREST_G4=OFF -DINSTALL_PREFIX=${CI_PROJECT_DIR}/install
    - make install -j2
    - . ${CI_PROJECT_DIR}/framework/source/libraries/axion/external/solarAxionFlux/bin/thisSolarAxionFluxLib.sh
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - restRoot -b -q
  except:
    variables:
      - $CRONJOB
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install
      - ${CI_PROJECT_DIR}/framework
    expire_in: 1 day

loadRESTLibs:
  type: loadRESTLibs
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - . ${CI_PROJECT_DIR}/framework/source/libraries/axion/external/solarAxionFlux/bin/thisSolarAxionFluxLib.sh
    - restRoot -b -q
  except:
    variables:
      - $CRONJOB

magneticField:
  type: metadata
  script:
    - . ${CI_PROJECT_DIR}/framework/source/libraries/axion/external/solarAxionFlux/bin/thisSolarAxionFluxLib.sh
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/pipeline/magneticField/
    - ./magneticField.py
    - cd trilinear
    - restRoot -b -q GetMagneticField_test.C
    - cd ${CI_PROJECT_DIR}/pipeline/magneticField/boundary/
    - restRoot -b -q Boundaries_test.C
  except:
      variables:
        - $CRONJOB
