image: nkx1231/root6-geant4-garfield:0.4

stages:
  - pre-build
  - build
  - loadRESTLibs

before_script:
  - export USER="test"
# - source /opt/ROOT/install/bin/thisroot.sh
  - apt -y update
  - apt -y install ssh-askpass
  - apt -y install libmpfr-dev libmpfr-doc libmpfr4 libmpfr4-dbg

clang-format:
    stage: pre-build
    script:
        - cd ${CI_PROJECT_DIR}/scripts/pipeline/clang-format/
        - ./clangformattest.sh
          # We execute only at a schedulled pipeline that defines CRONJOB variable
    only:
        variables:
            - $CRONJOB

build:
  type: build
  script:
    - mkdir /tmp/rest && cd /tmp/rest
    - echo "**${CI_PROJECT_DIR}**"
    - rm -rf ${CI_PROJECT_DIR}/install
    - ssh-keyscan -t rsa lfna.unizar.es >> ~/.ssh/known_hosts
    - git clone git@lfna.unizar.es:rest-development/REST_v2.git REST_v2
    - cd REST_v2/
    - git checkout development
    - mkdir build
    - cd build
    - cmake ../ -DREST_WELCOME=ON -DREST_GARFIELD=OFF -DREST_G4=OFF -DINSTALL_PREFIX=${CI_PROJECT_DIR}/install
    - make install -j2
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - restRoot -b -q
    - cd ${CI_PROJECT_DIR}
    - mkdir build
    - cd build
    - cmake ../
    - make install -j2
    - restRoot -b -q
  except:
    variables:
      - $CRONJOB
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install
    expire_in: 1 day

loadRESTLibs:
  type: loadRESTLibs
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
      # - root -b -q ${CI_PROJECT_DIR}/install/macros/pipeline/loadLibraries.C
    - restRoot -b -q
  except:
    variables:
      - $CRONJOB
