image: nkx1231/root6-geant4-garfield:0.8

variables:
      GIT_SUBMODULE_STRATEGY: recursive

stages:
  - pre-build
  - build
  - loadRESTLibs
  - metadata

before_script:
    - export USER="aXion"

# We execute only at the schedulled pipeline that defines CRONJOB variable
clang-format:
    stage: pre-build
    script:
        - echo "**$CRONJOB**"
        - echo "**$CI_SERVER_HOST**"
        - cd ${CI_PROJECT_DIR}/pipeline/clang-format/
        - ./clangformattest.sh
    only:
        variables:
            - $CRONJOB

validateLibrary:
    stage: pre-build
    script:
        - python pipeline/validateLibrary.py .
    except:
        variables:
            - $CRONJOB == "YES"

build:
  type: build
  script:
    - echo "**${CI_PROJECT_DIR}**"
    - rm -rf ${CI_PROJECT_DIR}/install
    - apt-get -y install libgmp-dev
    - wget https://www.mpfr.org/mpfr-4.0.2/mpfr-4.0.2.tar.gz
    - tar xvzf mpfr-4.0.2.tar.gz
    - cd mpfr-4.0.2/
    - ./configure
    - make
    - make install
    - cd ..
    - git clone https://github.com/rest-for-physics/framework.git framework
    - cd framework
    - ./scripts/checkoutRemoteBranch.sh ${CI_COMMIT_BRANCH}
    - git submodule init source/libraries/axion
    - git submodule update source/libraries/axion
    - cd source/libraries/axion/
    - git checkout ${CI_COMMIT_BRANCH}
    - cd ../../../
    - mkdir build
    - cd build
    - cmake ../ -DREST_SOLAXFLUX=OFF -DREST_WELCOME=ON -DRESTLIB_AXION=ON -DREST_GARFIELD=OFF -DREST_G4=OFF -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install
    - make install -j2
      #    - . ${CI_PROJECT_DIR}/framework/source/libraries/axion/external/solarAxionFlux/bin/thisSolarAxionFluxLib.sh
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - restRoot -b -q
  except:
    variables:
      - $CRONJOB
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install
      - ${CI_PROJECT_DIR}/framework
    expire_in: 1 day

loadRESTLibs:
  type: loadRESTLibs
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
      #    - . ${CI_PROJECT_DIR}/framework/source/libraries/axion/external/solarAxionFlux/bin/thisSolarAxionFluxLib.sh
    - restRoot -b -q
  except:
    variables:
      - $CRONJOB

magneticField:
  type: metadata
  script:
      #    - . ${CI_PROJECT_DIR}/framework/source/libraries/axion/external/solarAxionFlux/bin/thisSolarAxionFluxLib.sh
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/pipeline/magneticField/
    - which python
    - ls -lrth /usr/bin/pyt*
    - python magneticField.py
    - ls -lrth /usr/lib/
    - cd trilinear
    - restRoot -b -q GetMagneticField_test.C
    - cd ${CI_PROJECT_DIR}/pipeline/magneticField/boundary/
    - restRoot -b -q Boundaries_test.C
  except:
      variables:
        - $CRONJOB
